### PR TITLE
Decouple juniper

### PR DESCRIPTION
**Pull request by saacg**
For code review @portante @SahilTikale @naved001

### CODE REVIEW

**Comment by portante** [comment]
How does this commit reconcile with @vsemp's three and PRs #18 and #27?

**Review by portante — CHANGES_REQUESTED** [review]
Can you resolve the conflicts you have, and see about condensing into a smaller set of comments?  43 is a lot to review individually, and since you only have 13 files changes, it seems a bit much.

**Comment by saacg** [comment]
@portante just resolved the conflicts, and I had not yet condensed the commits using git rebase -i because I wanted to make sure that this would not affect branches that had been based off of this branch, as these commits had already been pushed. I believe you said you would discuss that with us at a later date? Should I just go ahead and rebase?

**Comment by saacg** [comment]
@portante to clarify how this pr relates to @vsemp's three and #27 (I closed #18): This branch, class/decouple-juniper, was the main branch for developing the abstraction design. When we began development, we were working with the idea that #39 and this branch would be alternative solutions, and thus we would want to keep them in their own separate branches, as we would never merge them together in master.

 #27 was a branch that @Hugh472 had been working off of to make changes to HilDriver.py. However, based on our updated design (see next paragraph), this may now be deprecated anyway and perhaps can be closed? 

Based on our last meeting, we decided to progress our abstraction design by breaking down hardware_service.py into two new classes, inventory_service and network_service (never decided on name for this class, just using network_service for now). As this branch has our most up-to-date code for this design, when @vsemp had some ideas about how to structure the break down of functions, I requested that he branch off this branch, and make a pr to it when he was ready, so we could easily identify the new changes and see if there would be any major conflicts. This accounts for pr #43. I am not sure of the purpose of #37, as I thought most of these changes also appear in #43.  

I now completely appreciate the importance of having well documented comments and commit messages, especially when making a pr.

**Comment by saacg** [comment]
closed as it has been superseded by newer changes.

**Pull request closed without merging**
