### PR TITLE
Update class master

### PR DESCRIPTION
**Pull request by saacg**
rebasing our class/master branch to stay up to date with upstream/master commits

### CODE REVIEW

**Comment by saacg** [comment]
@portante

**Comment by vsemp** [comment]
Did Red-Hat write new commits recently?

**Comment by saacg** [comment]
@vsemp yes. If you look at our class/master, it currently says we are behind upstream by 4 commits.

**Comment by vsemp** [comment]
Were you able to rebase all our ~70 commits?

**Comment by saacg** [comment]
Yeah, there was only one minor conflict, and it did the rest automatically.

**Comment by portante** [comment]
This doesn't look right.  You should just have the 4 commits from upstream, no?

**Comment by vsemp** [comment]
Thanks, Isaac.

**Comment by saacg** [comment]
Yeah @portante I'm not sure. 
This is what I did:
git remote update
git checkout -b update-class-master class/master
git branch --set-upstream-to=upstream/master
git rebase

**Comment by portante** [comment]
@saacg, I think you did the right steps, but after reviewing, the changes don't seem to be significant enough to take in at this point, and the final step would be to "`git push --force class update-class-master:master`", since we are keeping this as a rebase on top of `upstream`.

**Comment by portante** [comment]
Let's not do this now.

**Pull request closed without merging**
